sudo: false

language: node_js

node_js:
      - "4.1"

services:
    - docker

before_install:
    - docker build -t jekkos/opensourcepos .
    - docker run -d jekkos/opensourcepos 

script:
    - docker exec -t -i $(docker ps | tail -n 1 | cut -d' ' -f1) /bin/sh -c "while ! curl http://localhost/index.php | grep username; do sleep 1; done; cd app && grunt mochaWebdriver:test" 
